{{- if .Values.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shpod.fullname" . }}
  labels:
    {{- include "shpod.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{ .Values.persistentVolume.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  {{- with .Values.persistentVolume.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
