{{- if .Values.rbac.enabled -}}
{{- range .Values.rbac.cluster.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{
    printf "%s-%s-%s" 
    $.Release.Namespace (include "shpod.fullname" $) .
    }}
  labels:
    {{- include "shpod.labels" $ | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ . }}
subjects:
- kind: ServiceAccount
  name: {{ include "shpod.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- range .Values.rbac.namespace.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{
    printf "%s-clusterrole-%s" 
    (include "shpod.fullname" $) .
    }}
  labels:
    {{- include "shpod.labels" $ | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ . }}
subjects:
- kind: ServiceAccount
  name: {{ include "shpod.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- range .Values.rbac.namespace.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{
    printf "%s-role-%s" 
    (include "shpod.fullname" $) .
    }}
  labels:
    {{- include "shpod.labels" $ | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ . }}
subjects:
- kind: ServiceAccount
  name: {{ include "shpod.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
