apiVersion: v1
kind: Service
metadata:
  name: {{ include "shpod.fullname" . }}
  labels:
    {{- include "shpod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "shpod.selectorLabels" . | nindent 4 }}
