# Default values for shpod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/jpetazzo/shpod
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

#This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/ 
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 22

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
readinessProbe:

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

# These values are inspired by the ones in the Prometheus chart.
# (https://artifacthub.io/packages/helm/prometheus-community/prometheus)
persistentVolume:
  ## If true, we will create and use a PVC for $HOME.
  ## If false, we'll use an emptyDir instead.
  enabled: false
  ## The remaining values are used only when "enabled" is true.
  accessModes:
    - ReadWriteOnce
  size: 1G
  storageClass: null

rbac:
  ## If rbac.enabled=false:
  ## no RoleBinding or ClusterRoleBinding will be created.
  enabled: true
  cluster:
    ## rbac.cluster.clusterRoles:
    ## list of ClusterRoles that should be granted to the ServiceAccount, cluster-wide.
    clusterRoles: []
  namespace:
    ## rbac.namespace.clusterRoles:
    ## list of ClusterRoles that should be granted to the ServiceAccount, only in the application Namespace.
    clusterRoles: [ view ]
    ## rbac.namespace.roles:
    ## list of Roles that should be granted to the ServiceAccount in the application Namespace.
    roles: []

ssh:
  ## If SSH is enabled, you can connect to shpod with an SSH client
  ## or with "kubectl exec".
  ## If SSH is disabled, you cannot connect to shpod with SSH,
  ## but you can use "kubectl exec" or "kubectl attach".
  enabled: true
  ## If password is not set, a random password will be generated
  ## and displayed in the container log.
  password: ""
