# Note: by default this workflow assumes that your github user name = your Docker Hub user name.
# You can force it using `with: {DOCKER_HUB_USERNAME: myuser}` in the calling workflow
# It will also probably break for GitHub users or repositories with uppercase letters.

name: Automated Build

on:
  workflow_dispatch:
    inputs:
      PLATFORMS:
        required: false
        type: string
        default: 'linux/amd64,linux/arm64,linux/arm/v7'

env:
  DOCKER_BUILDKIT: 1

jobs:
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Set environment variables
        run: |
          IMAGES=""
          if true; then
            echo PUSH_TO_GHCR=yes >> $GITHUB_ENV
            IMAGES="$IMAGES ghcr.io/${{ github.repository }}"
          fi
          echo 'IMAGES<<EOF' >> $GITHUB_ENV
          for IMAGE in $IMAGES; do
            echo $IMAGE >> $GITHUB_ENV
            if [ "$GITHUB_REF_TYPE" == "tag" ]; then
              echo $IMAGE:$GITHUB_REF_NAME >> $GITHUB_ENV
            fi
          done
          echo 'EOF' >> $GITHUB_ENV

      - 
        uses: actions/checkout@v3

      -
        name: Log into GitHub Container Registry
        if: env.PUSH_TO_GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      -
        uses: docker/setup-qemu-action@v2

      -
        uses: docker/setup-buildx-action@v2

      -
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ inputs.PLATFORMS }}
          push: true
          tags: ${{ env.IMAGES }}
